name: Test 
on:
  schedule:
    - cron: "30 10 * * *" # 00:00 1st of every month

jobs:
    run-python-test:
        runs-on: ubuntu-latest
        name: "Run Python Test"
        steps:
            - name: checkout repo content
              uses: actions/checkout@v2
      
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
      
            - name: install python packages
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            - name: Configure AWS Creds - Staging
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - name: execute python script
              run: python test_script.py